// Copyright 2026 Nekzus Solutions and contributors
// SPDX-License-Identifier: Apache-2.0

import crypto from "node:crypto";

export interface ZkReceipt {
	/** Cryptographic proof generated by a zero-knowledge VM (e.g., RISC Zero, SP1) */
	proof: Buffer;
	/** The public inputs/outputs of the execution (the "Journal" in RISC Zero terminology) */
	journal: Buffer;
	/** The expected image ID / verification key of the WASM binary that was executed */
	imageId: Buffer;
}

export class ZkVerificationError extends Error {
	constructor(message: string) {
		super(`ZK Verification Failed: ${message}`);
		this.name = "ZkVerificationError";
	}
}

/**
 * ZK-Proofs Verifier for Logic-Injection-on-Origin Protocol (LIOP)
 *
 * Validates that an executed Logic (WASM) actually produced the reported output,
 * verifying the Zero-Knowledge receipt generated by the remote host's Trusted Execution
 * Environment (TEE) or zkVM (Zero-Knowledge Virtual Machine).
 */
export const ZkVerifier = {
	/**
	 * Validates a ZK receipt using structural Binary Receipt verification.
	 * Parses the HMAC-SHA256 commitment format (v1) and verifies journal integrity.
	 *
	 * @param receipt - Complete ZkReceipt to verify
	 * @param expectedImageId - Hash or ImageID of the WASM file dispatched to the host
	 * @throws ZkVerificationError if the proof is invalid or image IDs mismatch
	 * @returns true if the proof mathematically verifies the execution
	 */
	verify(
		receipt: ZkReceipt,
		expectedImageId: Buffer,
		sessionSecret?: Buffer,
	): boolean {
		// 1. Verify Image ID (Ensures the host executed the exact logic we sent, not a malicious one)
		if (!receipt.imageId.equals(expectedImageId)) {
			throw new ZkVerificationError(
				"ImageID mismatch. The remote origin executed a different WASM payload.",
			);
		}

		// 2. Validate Proof Structure
		if (receipt.proof.length === 0) {
			throw new ZkVerificationError(
				"Empty or malformed zero-knowledge proof array.",
			);
		}

		// 3. Cryptographic Validation (Binary Receipt)
		const proofBuf = Buffer.from(receipt.proof);
		if (proofBuf.length < 35 || proofBuf[0] !== 0x01) {
			throw new ZkVerificationError(
				"Malformed receipt: invalid header or length.",
			);
		}
		const journalLen = proofBuf.readUInt16BE(1);
		const journal = proofBuf.subarray(3, 3 + journalLen);
		const seal = proofBuf.subarray(3 + journalLen);

		if (seal.length !== 32) {
			throw new ZkVerificationError(
				"Invalid seal: expected 32-byte HMAC-SHA256.",
			);
		}

		// Verify journal contains matching imageId
		try {
			const journalData = JSON.parse(journal.toString());
			if (journalData.image_id !== receipt.imageId.toString("hex")) {
				throw new ZkVerificationError(
					"Journal imageId does not match receipt header.",
				);
			}
		} catch (_e) {
			throw new ZkVerificationError("Failed to parse journal data.");
		}

		// 4. Mathematical Verification (HMAC-SHA256)
		if (sessionSecret && sessionSecret.length > 0) {
			const expectedSeal = crypto
				.createHmac("sha256", sessionSecret)
				.update(journal)
				.digest();
			if (!crypto.timingSafeEqual(seal, expectedSeal)) {
				throw new ZkVerificationError(
					"Invalid seal: HMAC verification failed.",
				);
			}
		}

		return true;
	},

	/**
	 * Derives a predictable ImageID (usually a Hash) from a raw WASM binary.
	 *
	 * @param wasmBytes - The raw bytes of the WASM logic file
	 * @returns The SHA-256 ImageID of the logic
	 */
	deriveImageId(wasmBytes: Buffer): Buffer {
		return crypto.createHash("sha256").update(wasmBytes).digest();
	},
};
