// Copyright 2026 Nekzus Solutions and contributors
// SPDX-License-Identifier: Apache-2.0

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use tracing::info;

/// LIOP Zk Receipt
/// This struct travels through the LIOP gRPC Payload so that the Client
/// (TS SDK or AI Agent) verifies the execution.
#[derive(Serialize, Deserialize, Debug)]
pub struct LiopZkReceipt {
    pub journal: Vec<u8>,
    pub seal: Vec<u8>, // The ZK-SNARK mathematical proof
}

/// Request injected by the Host into the Guest (WASM + Files)
#[derive(Serialize, Deserialize, Debug)]
pub struct ZkExecutionRequest {
    pub wasm_logic: Vec<u8>,
    pub input_data: Vec<u8>,
}

/// Response Generated and Secured by the zkVM
#[derive(Serialize, Deserialize, Debug)]
pub struct ZkExecutionResult {
    pub output: String,
    pub is_valid: bool,
}

/// ImageID of the precompiled RISC-V ELF WASM Interpreter
/// (This constant would be generated by `cargo risczero build` in a real workspace)
pub const ZK_WASM_GUEST_ID: [u32; 8] = [0, 0, 0, 0, 0, 0, 0, 0];
pub const ZK_WASM_GUEST_ELF: &[u8] = &[];

pub struct ZkExecutionEngine;

impl ZkExecutionEngine {
    /// Generates the Zero-Knowledge mathematical proof for a WASM processing
    /// confidential data.
    /// Returns (Execution Result, Bincode Serialized Proof).
    pub fn prove_wasm_execution(
        _wasm_logic: &[u8],
        _input_data: &[u8],
    ) -> Result<(ZkExecutionResult, Vec<u8>), Box<dyn std::error::Error>> {
        info!("ZK: Initializing RISC Zero ZK-VM Prover (Stub)");

        // IMPORTANT: In local development on Windows, RISC Zero fails
        // due to Unix dependencies (os::unix::net::UnixStream).
        // Prove function takes the ELF and the environment setup.
        info!("ZK: Generating computational receipt based on payload");

        // let prove_info = prover.prove(env, ZK_WASM_GUEST_ELF)?;
        // let receipt = prove_info.receipt;

        let stub_result = ZkExecutionResult {
            output: "ZK_PROVED_RESULT".to_string(),
            is_valid: true,
        };

        // Generate Cryptographic Mock of the Journal (Derived ImageID)
        let mut journal_hasher = Sha256::new();
        journal_hasher.update(_wasm_logic);
        let journal_hash = journal_hasher.finalize().to_vec();

        // Generate Cryptographic Mock of the Seal
        let mut seal_hasher = Sha256::new();
        seal_hasher.update(&journal_hash);
        seal_hasher.update(_input_data);
        seal_hasher.update(b"ZK_SNARK_STUB_SEAL");
        let seal_hash = seal_hasher.finalize().to_vec();

        let liop_receipt = LiopZkReceipt {
            journal: journal_hash,
            seal: seal_hash,
        };

        let receipt_bytes = bincode::serialize(&liop_receipt)?;

        Ok((stub_result, receipt_bytes))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn receipt_is_deterministic_for_same_input() {
        let wasm = b"test_wasm_binary";
        let input = b"test_input_data";

        let (result1, bytes1) = ZkExecutionEngine::prove_wasm_execution(wasm, input).unwrap();
        let (result2, bytes2) = ZkExecutionEngine::prove_wasm_execution(wasm, input).unwrap();

        assert!(result1.is_valid);
        assert!(result2.is_valid);
        assert_eq!(
            bytes1, bytes2,
            "Identical inputs must produce identical receipts"
        );
    }

    #[test]
    fn receipt_differs_for_different_wasm() {
        let input = b"shared_input";
        let (_, bytes_a) = ZkExecutionEngine::prove_wasm_execution(b"wasm_v1", input).unwrap();
        let (_, bytes_b) = ZkExecutionEngine::prove_wasm_execution(b"wasm_v2", input).unwrap();

        assert_ne!(
            bytes_a, bytes_b,
            "Different WASM logic must produce unique receipts"
        );
    }

    #[test]
    fn receipt_differs_for_different_input_data() {
        let wasm = b"same_wasm";
        let (_, bytes_a) = ZkExecutionEngine::prove_wasm_execution(wasm, b"input_a").unwrap();
        let (_, bytes_b) = ZkExecutionEngine::prove_wasm_execution(wasm, b"input_b").unwrap();

        assert_ne!(
            bytes_a, bytes_b,
            "Different input data must produce unique seals"
        );
    }

    #[test]
    fn receipt_deserializes_correctly() {
        let wasm = b"deserialize_test";
        let (_, bytes) = ZkExecutionEngine::prove_wasm_execution(wasm, b"").unwrap();

        let receipt: LiopZkReceipt =
            bincode::deserialize(&bytes).expect("Receipt should deserialize from bincode");

        assert_eq!(
            receipt.journal.len(),
            32,
            "Journal should be SHA-256 (32 bytes)"
        );
        assert_eq!(receipt.seal.len(), 32, "Seal should be SHA-256 (32 bytes)");
    }

    #[test]
    fn receipt_works_with_empty_inputs() {
        let result = ZkExecutionEngine::prove_wasm_execution(b"", b"");
        assert!(
            result.is_ok(),
            "Empty inputs should still produce a valid receipt"
        );
    }
}
